import json

input_file = "clean.json"
output_file = "generated.sql"

table_name = "companies"

columns = {
    0: "id",
    1: "company_name",
    2: "brand",
    3: "industry",
    4: "manager_name",
    5: "phone_number",
    6: "address",
    7: "postal_code",
    8: "unit_number"
}

try:
    with open(input_file, "r", encoding="utf-8") as file:
        data = json.load(file)
except Exception as e:
    print(f"Error reading JSON file: {e}")
    exit()

data = data.get("data", [])
if not isinstance(data, list) or len(data) == 0:
    print("Invalid or empty data in JSON file. Ensure 'data' contains a list.")
    exit()

create_table_command = f"CREATE TABLE IF NOT EXISTS {table_name} (\n"
for index, column_name in columns.items():
    if index == 0:
        create_table_command += f"    {column_name} INT AUTO_INCREMENT PRIMARY KEY,\n"
    else:
        create_table_command += f"    `{column_name}` TEXT,\n"
create_table_command = create_table_command.rstrip(",\n") + "\n);\n\n"

insert_commands = []
for row in data:
    values = []
    for index, column_name in columns.items():
        value = row[index] if index < len(row) else ""
        values.append(f"'{value}'" if isinstance(value, str) else str(value))
    insert_commands.append(
        f"INSERT INTO {table_name} ({', '.join(columns.values())}) VALUES ({', '.join(values)});"
    )

try:
    with open(output_file, "w", encoding="utf-8") as file:
        file.write("-- SQL Script Generated by Python\n\n")
        file.write(create_table_command)
        file.write("\n".join(insert_commands) + "\n")
    print(f"SQL script '{output_file}' has been generated.")
except Exception as e:
    print(f"Error writing SQL file: {e}")
